# For use with Spiki: https://pypi.org/project/spiki/
[base]
config = {tag_mode = "open"}
"!doctype html" = ""

[base.html]
config = {tag_mode = "pair"}
attrib = {lang = "en"}

[base.html.head]
title = "{metadata[title]}"

[[base.html.head.meta]]
config = {tag_mode = "void"}
attrib = {charset = "UTF-8"}

[[base.html.head.meta]]
config = {tag_mode = "void"}
attrib = {name = "viewport", content = "width=device-width, initial-scale=1.0"}

[[base.html.head.meta]]
config = {tag_mode = "void"}
attrib = {http-equiv = "X-UA-Compatible", content = "ie=edge"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "preconnect", href = "https://fonts.googleapis.com"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = "crossorigin"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "stylesheet", href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,100..900;1,100..900&display=swap"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "stylesheet", href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&display=swap"}
